import { Provider } from 'react-redux'
// import './globals.css'
import { Holtwood_One_SC, Inter } from 'next/font/google'
import { store } from '../redux/store'
// import { AppProvider } from '../redux/AppProvider'
import { Footer, Header, Main } from '../components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
        title: 'Doctor page',
        description: 'Generated by doctors',
}

export default function RootLayout({
        children,
}: {
        children: React.ReactNode
}) {
        return (

                <Main>
                        <Header />
                        <div className='doctor-dashboard'>
                                {children}
                        </div>
                        <Footer />
                </Main>


        )
}
